### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by robgal519** [mjradwin/stubgen#8]
When I tried to compile the project, I got compilation error:

make all
flex lexer.l
gcc -Wall -Werror -g -O2 -DSGDEBUG   -c -o lex.yy.o lex.yy.c
gcc -Wall -Werror -g -O2 -DSGDEBUG   -c -o table.o table.c
table.c:50:19: error: ‘rcsid’ defined but not used [-Werror=unused-const-variable=]
 static const char rcsid[] = "$Id: table.c,v 1.28 1998/06/11 14:52:09 mradwin Exp $";
                   ^~~~~
cc1: all warnings being treated as errors
<wbudowane>: recipe for target 'table.o' failed
make: *** [table.o] Error 1

I worked around this issue by disabling -Werror in makefile, but in my opinion this type of error could be easily fixed ( it's wired that Travis did not found it)

**Comment by mjradwin** [comment]
Thanks for this bug report. We can get this small issue fixed.

Please note that this package was developed in 1996, and as such predates the C++03 and more modern standards. It's not guaranteed to work well with modern C++.
